import { AiFillStar } from "react-icons/ai";

export const products = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹40,00",
    newPrice: "2000",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: AiFillStar,
    reviews: "(56 reviews)",
    prevPrice: "₹70,00",
    newPrice: "3500",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹4500",
    newPrice: "2000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2500",
    newPrice: "1500",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹3000",
    newPrice: "2000",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹7999",
    newPrice: "4999",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹14,00",
    newPrice: "599",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹100,00",
    newPrice: "7000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹7000",
    newPrice: "4000",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹4000",
    newPrice: "1500",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Puma Pacer Future Sneaker",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹40,00",
    newPrice: "2500",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Puma Unisex-Adult Super",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹10,00",
    newPrice: "400",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Puma Roma Basic Sneaker",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹140,0",
    newPrice: "990",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Puma Pacer Future Doubleknit",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1000",
    newPrice: "799",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Puma Fusion Evo Golf Shoe",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1900",
    newPrice: "1400",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Vans Rainbow Chex Skate",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1000",
    newPrice: "700",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Vans Low-Top Trainers",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹13,00",
    newPrice: "1000",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1500",
    newPrice: "999",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1400",
    newPrice: "799",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Vans Chunky High Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1500",
    newPrice: "599",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Puma Slip On Stiletto High Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1700",
    newPrice: "1000",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1600",
    newPrice: "1500",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹10000",
    newPrice: "6999",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹30,00",
    newPrice: "2150",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Adidas Chunky High Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2500",
    newPrice: "1500",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "300",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹900",
    newPrice: "500",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal Heel",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2400",
    newPrice: "1900",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/n/k/z/7-sm-773-sparx-grey-original-imagjhkwfmq6x3fu.jpeg?q=70",
    title: "Sparx SM 773_AB Running Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2400",
    newPrice: "1500",
    company: "Sparx",
    color: "black",
    category: "Sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/q/e/7-sm-724-sparx-black-original-imagjgcsvegrhbxw.jpeg?q=70",
    title: "Sparx Walking Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹1900",
    newPrice: "1300",
    company: "Sparx",
    color: "black",
    category: "Sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/7/3/i/9-sm-724-sparx-grey-original-imagjs8h9bjpfh85.jpeg?q=70",
    title: "Sparx Running Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2000",
    newPrice: "1300",
    company: "Sparx",
    color: "white",
    category: "Sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/81xukHbw7yL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Sparx Mens Sx0812g Sneaker",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹3000",
    newPrice: "1800",
    company: "Sparx",
    color: "white",
    category: "Sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kl2mljk0/shoe/k/q/k/7-sm-661-white-black-41-sparx-white-original-imagyafnjyqbzejz.jpeg?q=70",
    title: "Sparx Comfirtable Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹200",
    newPrice: "1300",
    company: "Sparx",
    color: "white",
    category: "Sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61-G2UDgjiL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Campus Men's North Plus Running Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2000",
    newPrice: "1500",
    company: "Campus",
    color: "black",
    category: "Sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61ePa5fEKnL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Campus Men's OXYFIT (N) Walking Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2000",
    newPrice: "1500",
    company: "Campus",
    color: "blue",
    category: "Sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71xogfKzNQL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Campus Men's First Running Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2000",
    newPrice: "1500",
    company: "Campus",
    color: "white",
    category: "Sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61S-SfSwsML._AC_UL480_FMwebp_QL65_.jpg",
    title: "Campus Men's FANSHOE-2 Running Shoes",
    star: AiFillStar,
    reviews: "(123 reviews)",
    prevPrice: "₹2000",
    newPrice: "1600",
    company: "Campus",
    color: "green",
    category: "Sneakers",
  },
];
